### ISSUE TITLE
Minutes from last meeting?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#1]
Lina, where were the minutes from the last meeting? Could we put them up here in this repo?

Or is there another location others can think of or suggest?

**Comment by lwjohnst86** [comment]
I don't know how this assigning thing works... haha...

**Comment by linamnt** [comment]
Lol np, it's up now and I'll make sure to get them up for the next meeting promptly!

**Comment by lwjohnst86** [comment]
Thanks :smiley:
