### ISSUE TITLE
Decide on focus teaching areas for next year

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/council#115]
This was originally the graduate workshop issue for Luke and Lina. However, before getting into that, I think it is worth discussing what we want to focus on for next year in terms of teaching. These are the ideas we have been discussing so far.

- Regular UoftCoders meetings
- RQM course
- Additional meetings once a month on a co-working topic
- Workshops for grad students
- Software Carpentry
- Data Carpentry
- Workshops hosted by others, similar to the digital information workshop and the Ryerson one.

I think it will be too much if we do all these things. This is something to discuss next meeting maybe?

**Comment by mbonsma** [comment]
From this list, the only things we're not already doing or won't be doing for sure are:
* workshops for grad students
* additional monthly coworking meetings
* Data Carpentry. 

I agree that it's good to think about whether or not we're taking on too much, but I also think that there is a lot of enthusiasm from extremely capable people (aka you fine exec folks), and if the new activities have a champion (i.e. @linamnt for the monthly group project), then it's totally doable. Data Carpentry is exactly like Software Carpentry except for the material as far as I know, so it's just a question of finding willing instructors and helpers. Whether or not the organizational part becomes too much work is up to @lcoome. Was the workshops for grad students thing a product of one of our conversations about RQM? I agree, maybe that one can go on the back burner.

**Comment by lwjohnst86** [comment]
I agree that we should definitely be mindful of keeping the workload manageable. But as @mbonsma said, we seem like pretty darn capable people! :smile: I'll also be a lot more free in the fall term (possibly the summer too.. depending on thesis stuff), so I can help more with whatever we have planning for that time span.

The workshops for grad students I think was based on what I've done with GPS and also in conjunction with the RQM course. It could be that depending how we structure the course, it could be modular enough that it would be fairly easy to teach components of it for GPS and/or other groups (Mitacs maybe?). And might not necessarily be much more work aside from the time teaching.
