### ISSUE TITLE
Make posters to advertise the group more widely

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/council#120]
- [ ] Make posters (US Letter size) to put up around campus. @lcoome do you want to do this in the same style of the software carpentry workshop posters you made? If not, I can ask a friend of mine, but I am not sure that she will have the time.
    - [ ] Think about permissions for posters, and assign people buildings. We don't have to put up everything at once, let's start with our individual buildings and evaluate the response. 
    - [ ] QR code potentially
    - [ ] Printing: Joel and Madeleine might have access to color printer

**Comment by lcoome** [comment]
Definitely will make posters, could potentially print them too - we just need to discuss what copy we want on them

________________________________

**Comment by joelostblom** [comment]
Great! I modified this issue to be for the posters only and moved the rest of the advertisement items to #128. If you have any suggestions in mind for design/content, just post about it here, otherwise we can brainstorm ideas on the next meeting.
