### ISSUE TITLE
Create attendance/survey sheet

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/council#121]
To be passed around each session.
- Only new people have to sign up, everyone can still check of their name so that we can keep attendance.
- How did you hear about us?
- Email for newsletter
- Send them thank you email with a few survey questions?

**Comment by linamnt** [comment]
Okay we have one made and ready to go starting next week. We'll see pretty quickly if it's worth continuing or if people even fill it out (I hope!!)
