### ISSUE TITLE
Offer tea at regular meetings

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/council#123]
- [x] Buy kettle (max $40)
- [x] Buy teabags?
- [ ] Buy papermugs (keep hidden offer if necessary)
- [ ] Serve the first cup at a meeting

**Comment by lwjohnst86** [comment]
Done! Tho I haven't bought paper cups. I'll bring them to the meeting :smile:

**Comment by mbonsma** [comment]
Our hero! :clap: :clap:
