### ISSUE TITLE
Apply for funding from UofT?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/council#124]
In the previous student club I was part of, we applied for funding from many places within UofT. It was quite a lot of work, but we also got a substantial amount of money. Is this something we are interested in and are we eligible for anything although we primarily have grad students and not undergrads?

Something like this for the engineering faculty http://mse.utoronto.ca/current/student-life/funding/

**Comment by mbonsma** [comment]
Also see #31.

**Comment by joelostblom** [comment]
Closing and adding comment to #31 instead
