### ISSUE TITLE
Modify and send out survey for lesson topics and general feedback

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/council#125]
- [ ] Have a look [at the old survey](https://docs.google.com/forms/d/1j3r4Aup_SQbNjDf_y-cyBmZIyRVMAlM0j9Z55oXi9ss/viewform?edit_requested=true)
- [ ] Suggest topics to add or remove
    - Some core intro sessions in the beginning of the semester, then by popularity.
- [ ] Split it questions into topic sections?
- [ ] Send survey to members

**Comment by mbonsma** [comment]
I'm going through the old survey and clarifying some of the options based on the "other" responses.

**Comment by joelostblom** [comment]
Suggestions:

#### First st page
- Q1: "Google search" --> "Internet search" (Where's the love for DuckDuckGo ad StartPage?)
- Q3: Order alphabetically

#### Last page
- Q2: Potentially do the same thing as for Q3 below, although this is not as messy, so it could be enough just to sort alphabetically.  
- Q3: Group topics by prefacing all alternative with the language name and sort alphabetically, e.g. "Debugging in Python" --> "Python: Debugging".

#### Topics to add
These are areas I'm interested to learn about myself and it would be cool if someone could share their knowledge.
- Intro to functional programming, Haskell or Lisp?
- Testing and continuous integration with Travis CI or similar (maybe covered in the Python testing lecture already?)
- Intro to GPU computing in Python
- Intro to quantum computing... yes that might be asking for too much, but just the fact that we meet in the physics building means this is probably as close as I will ever to get to someone who knows quantum computing. It would be so cool to see a practical example of actually computing something, and not only theory. IBM has a [publicly accessible quantum computer](https://quantumexperience.ng.bluemix.net/qstage/#/user-guide).

**Comment by joelostblom** [comment]
I just got the invitation to edit the survey, should I change according to what I wrote above? what do you agree/disagree with?

**Comment by mbonsma** [comment]
I changed the first page, but not the last page. I'd say go ahead!

**Comment by joelostblom** [comment]
Added all my suggestions except for quantum computing... will fill that in the "other" box when I take the survey myself.

**Comment by linamnt** [comment]
Maybe we should make a copy of this, name it UofT Coders Survery - April 2017 or something, and start fresh with the responses so all the votes going to the previous answers don't cover up new insights we get from the new responses?

**Comment by joelostblom** [comment]
Agree

**Comment by mbonsma** [comment]
Sure - I already made a copy of the original version just to have a record of the old questions, but I agree we can also make a new copy so that the responses are somewhere different.
