### ISSUE TITLE
Recruit instructors for DHN

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/council#126]
- We have a lot of freedom here. Suggested topics html, image manipulation, text analysis, bash, web scraping, Python focus, pandoc etc.
- Two days (half day chunks, last chunk is electives, or lightning demos and rest is SWC)
- Tentative dates: May 22-23 (note: Victoria Day)
- Find out more info about what problems they are interested in solving?

- [x] Make survey for UofTCdrs and suggest dates based on availability?

**Comment by mbonsma** [comment]
I made a [survey](https://docs.google.com/forms/d/1sJ2UCv9rmR1OCE_aoBpthoGRkEqLWlaNAoV4CZQBmDY/edit?usp=sharing), and here's the blurb I'll be sending. Feedback/edits welcome, I'm hoping to send it out today.

-----------
Hi everyone,

The Digital Humanities Network and Jackman Humanities Institute at UofT in collaboration with UofT Coders will be holding a two-day workshop in May for digital humanities practitioners, and we are looking for instructors! The workshop material is flexible depending on instructor interest and availability of lesson material. Potential topics include HTML, automating tasks with the command line, image processing, natural language processing, regular expressions, and preserving and archiving data. If you're interested in developing lesson content and/or instructing for a portion of the workshop, please fill out this very short survey about topics and availability: https://goo.gl/forms/qwFwvEqJxVTCkYrD3 

You don't need to be an expert in your chosen topic to be a successful instructor!

Cheers,

Madeleine for UofT Coders

-----------

**Comment by linamnt** [comment]
That looks good to me, just added a quick definition of what lightning demos are in the survey, otherwise looks good!

**Comment by mbonsma** [comment]
Actually no rush anymore because I think they're going to book the room and then we can just send out the call with the specific date information. Should happen early next week.

**Comment by joelostblom** [comment]
Looks good!

I filled in the form. For image analyses, I'm mostly interested in helping out with lecture content if needed. A few resources: If we want to keep it straightforward, [simpleCV](http://simplecv.org/) looks like an interesting alternative to [openCV](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_tutorials.html). We could also base the lecture of the [user guide for scikit-image](http://scikit-image.org/docs/stable/user_guide.html).
