### ISSUE TITLE
update constitution with new position

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#17]
I think this will need to be done next academic year right? When we have to renew our Ulife status.

**Comment by linamnt** [comment]
Sorry I forgot to reply to this! Yes, we can do it for the new academic year which we can do soon (I can do it once I'm back mid-July) and add the description.

**Comment by lwjohnst86** [comment]
Repo has been updated #25, now need to add to  ULife status.

**Comment by lwjohnst86** [comment]
@linamnt submitted the updated constitution to Ulife. (that right?) so closing
