### ISSUE TITLE
Touch base with Christie, send the syllabus and inform that the course is happening

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/council#174]

**Comment by lwjohnst86** [comment]
Any word of if she got the job she applied to here? (was it Scarborough?) If she is coming here, and depending on logitistics, it might be good to have her continue/take over the course for long-term sustainability of it. That way it doesn't fizzle out after we all leave (though I really hope we can get it to be fairly sustainable)

**Comment by joelostblom** [comment]
@linamnt and @mbonsma mentioned that Christie [tweeted that she got hired elsewhere](https://twitter.com/cbahlai/status/867783794530676738)

**Comment by joelostblom** [comment]
This issue was moved to UofTCoders/rcourse#12
