### ISSUE TITLE
Members listing on uoftcoders website, change to "recurrent instructors"?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#176]
I've been thinking about this for a bit. On our website, we have a listing of the "members" of UofT Coders. For any one looking at the group, they may think that this group has few members, when in fact we have many more watching the repo and on the mailing list. 

What do you all think about instead converting the "Members" listing to a "Recurrent Instructors and Contributors" listing instead? That way it can give more credit to those who contribute to the group, while also reducing the potential perspective that the group is small (since not every member is on the listing).

Thoughts?

**Comment by joelostblom** [comment]
It sounds like a good idea to me! I don't think emphasizes that they are recurrent is needed and I would shorten to either "Instructors and contributors" or just "Contributors".

On this note, I think we should change our heading from "Administration", to something with more "umph!" (without sounding pretentious). Some suggestions:

- Executive team/board
- Executives
- Core team/developers/instructors
- Board
- Council
- Committee

**Comment by QuLogic** [comment]
Hmm, GitHub seems a bit overzealous here given the PR hasn't been merged and the referenced commit is not even in this repo.

**Comment by lwjohnst86** [comment]
Ya, I saw that too... strange behaviour.
