### ISSUE TITLE
Buy mic for live streaming

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#181]
Maybe one that would be a bluetooth clip-on mic. So presenter can walk around.

**Comment by joelostblom** [comment]
Not sure what our budget is for this, we have [this one](https://www.amazon.ca/Blue-Microphones-Yeti-USB-Microphone/dp/B002VA464S/ref=sr_1_1?s=musical-instruments&ie=UTF8&qid=1522286607&sr=1-1&keywords=yeti) in lab and it is great. Plug and play via USB for al OSes. It is quite expensive, but maybe a [cheaper alternative from the same company](https://www.amazon.ca/Blue-Microphones-Snowball-iCE-Microphone/dp/B006DIA77E/ref=sr_1_4?s=musical-instruments&ie=UTF8&qid=1522286607&sr=1-4&keywords=yeti) could be a sound investment. In general I think our recordings are pretty good already though so not sure if we need a mic at all.

**Comment by mbonsma** [comment]
It would mostly be in case someone's on-board mic isn't working.
