### ISSUE TITLE
Add 'first-time attendee' box to sign-in sheet

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/council#227]
Idea from Sam at this week's event.

**Comment by linamnt** [comment]
I was also wondering if we actually wanna keep track of names, we don't use that info,and could free up space on the sheet?

**Comment by mbonsma** [comment]
Yeah, I agree. Maybe only ask for name and email if first time?

**Comment by linamnt** [comment]
Okay, so the only thing we'll keep track of if they've been before is field of study and program? I'd lump "how'd you hear about us" under the first-timer too.

**Comment by linamnt** [comment]
I've edited it on drive, but feel free to move anything around. If it's okay, I can print some starting for next week's lesson.

**Comment by mbonsma** [comment]
Sounds good!

**Comment by mbonsma** [comment]
I looked at it on Drive, it looks good!
