### ISSUE TITLE
Intro Routine at Our Sessions

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/council#242]
We talked a bit about having a consistent intro to our sessions at UofT Coders to get newcomers oriented and feel welcome, to remind people about our code of conduct, to plug our gitter channel for webinar style recordings etc. before we start into introductions. 

I think it can be a valuable thing to have this opening routine but would like to hear your thoughts etc. We can of course rotate the Speaker at our sessions too.

Here's how I think it could be structured, feel free to add, edit things you think are important!
- Welcome everyone, and remind people what UofT Coders is (a student group aimed building a community for sharing programming skills for research, we hold weekly sessions, everyone welcome etc.)
- Thank MADLab for hosting us (Mobile App Development Lab, with 3D printers and VR Set)
- We have a Code of Conduct which can be found on our website
- Invite people to join our Gitter and post questions/comments during the lesson, and remind them to sign the attendance sheet
- If people would like to instruct or get involved, they can talk to the Intro Speaker.
- Lead into introductions, start with yourself and go around the room.

**Comment by linamnt** [comment]
Ya that's a great idea re: instructing/getting involved! 

The code of conduct is on the website at the bottom near the Mozilla logo, but we could make it more prominent.

**Comment by linamnt** [comment]
Ya that would work and is short and succinct.It does currently say "race" but we can change it. 

Also along the lines of lesson timing etc, it's best maybe to do this about 6:05 or so depending on how many attendees there are (re: introductions)? It doesn't take too long (I timed myself and it's about 1-1 1/2 min depending how you say things) but then introductions can take a while to go around the room if we ever have 31 ppl in the audience again (woot!) and then the lesson can start promptly at 6:10.

**Comment by mbonsma** [comment]
Because I think the intros are so important, I would actually prefer to wait until 6:10 to start the introductions, that way most people will be included in them and people don't feel like they're barging in on something when they come on time.

**Comment by linamnt** [comment]
See #246 , we can reopen if we need to change the routine in the future :+1:
