### ISSUE TITLE
Checklist for event host

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/council#255]
Similar to the Intro Routine that Lina outlined (#242), it would be nice to have a list of things that the exec attending an event should do. Feel free to add to this if I missed anything!

### Before the event
- Set up the live stream 
    - Go to [youtube.com/my_live_events](https://www.youtube.com/my_live_events) 
    - Log in to the UofT Coders account 
    - Click `Schedule a new event`
    - Fill in the title and description, referring to the [event issue](https://github.com/UofTCoders/Events/issues)
    - Change the start time to the right time and date (this doesn't have to be super accurate, as long as you don't leave it at `Now`, which will launch the hangout right away.)
    - Click `Create event`
- Paste the link to the live stream video in the event issue (the youtube video link, not the hangout itself)
- Purchase a $10 thank-you gift card for the instructor

### At the start of the event 
- Set up the snacks, stickers, and sign-in sheet
- Start the live stream
    - Go to [youtube.com/my_live_events](https://www.youtube.com/my_live_events) 
    - Click 'Start hangout on air`
    - Click the icon to add participants and send the link to the instructor
    - Mute your mike and turn off your camera, make sure the instructor is screen-sharing
    - (Optional) Click `Present to everyone` under the presenter's icon and `Hide from broadcast` under your icon
    - Click `Start broadcast` once the event is about to start
- Make the intro announcements (#242) and have everyone introduce themselves

### During the event
- Circulate the attendance sheet
- Help with any learner issues that come up
- Check the live stream periodically
- Check the [Gitter Lobby](https://gitter.im/UofTCoders/Lobby)
- Write and sign a card for the instructor (this could be done ahead of time too)

### After the event
- Give the thank-you card to the instructor
- Put away the snacks - anything open should go in the fridge (ants)
- Turn off the projector and the lights

**Comment by joelostblom** [comment]
LGTM!

- Check the Gitter **Lobby**
