### ISSUE TITLE
Add live stream section to each event blurb?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/council#256]
This occurred to me when I was reading #255. It might not be obvious for people that we are live streaming the events, since this is not posted with the event description for each event. We usually add it as a new comment just before the event starts. Is this intentional to encourage people to attend the sessions in person, or would we be open to adding something like this to the event blurb:

> **Watch:** This event will be [streamed live](https://www.youtube.com/channel/UCfGUFz6EG5gBfRt8-du0jaA/videos?sort=dd&view=2&shelf_id=3&live_view=502). If you have questions during the live stream (or just want to chat with us), please ask in our [Gitter lobby](https://gitter.im/UofTCoders/Lobby) and we will forward your questions to the instructor! (Although we aim to live stream each event, there are sometimes technical difficulties so it's best to attend in person if you can.)

We could add specific links to each live stream, instead of linking the general section I just created for all upcoming live streams (but that's more work). I chose "watch" to go with our general "w"-theme in the event blurb.

**Comment by mbonsma** [comment]
Yeah I like this idea! I've thought about that too. The main reason I guess is that we usually don't make the live stream until right before the event. We could add it to the event setup that @SaraMati does, in which case the links would be ready ahead of time to put into the description.

**Comment by joelostblom** [comment]
Yes, I was also thinking that it would be added to the even setup!

**Comment by SaraMati** [comment]
I've been adding a line to the email I send out saying that they can watch the event issue for the link to the live stream (I  forgot for this week's). I was thinking of adding the line to the event issue template. I'll add the blurb you wrote, thanks

**Comment by mbonsma** [comment]
@SaraMati, how do you feel about setting up the live stream when you make the issues? The instructions are in issue #255.

**Comment by SaraMati** [comment]
Done: i.e. added to the event up to September 2018. Added to the R code that generates the future event issues + markdown file for the events webpage.
