### ISSUE TITLE
Numbers for attendance to the CUPE workshops?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#27]
Since we have a record for the SWC attendance, might be good to keep a record for other workshops we hold (ie. number registered, number attended, continued attendance rates, etc). Might be useful data later on :stuck_out_tongue_winking_eye:

**Comment by QuLogic** [comment]
I took some notes on who attended last week; @lcoome has it. Unfortunately, I don't know how many people showed up the first week.

**Comment by mbonsma** [comment]
The first week the seats were almost completely full - someone could count the chairs in that room and subtract 6 or 7?

**Comment by lwjohnst86** [comment]
@lcoome do we have the survey data? Does that have registration numbers as well? Did anyone attend the second session that could also give an estimate to the numbers? I counted the last session.

**Comment by QuLogic** [comment]
It's the first session for which we need numbers; I gave second week's numbers to @lcoome.

**Comment by lcoome** [comment]
I sent the survey to Ali and Cordelia who said they'd send it out, but either they haven't or there are zero responses. The attendance from the second week I added to the sticky note feedback google doc in the workshop folder:


https://docs.google.com/document/d/1z2tX4jTC6MHSSbVv8G_aHrkrQ41yC-97xFUBjNCdqTs/edit


23 the second week. I believe Cordelia had a sign in sheet the first week and should be able to speak to attendance for that.


Ricardo also inquired about the honorarium - when should we/can we distribute that?


________________________________

**Comment by lcoome** [comment]
Also - thanks to Elliott for taking attendance the second week! Smart idea.

________________________________

**Comment by lwjohnst86** [comment]
Honorariums will be distributed soon! Wanted to wait until I put the cheque into bank, which I did today!

**Comment by lcoome** [comment]
I assumed as much! Sounds perfect.

________________________________

**Comment by QuLogic** [comment]
Note that that document was set to "Can edit with the link", but GitHub is public, so I changed the link setting to "Can view" (and the fact that I could do so is why you should be careful sharing those links publicly.)

**Comment by lcoome** [comment]
Good catch!

________________________________
