### ISSUE TITLE
biomedical data science course: brainstorming 

### ISSUE THREAD

**Issue by SaraMati** [UofTCoders/council#286]
to follow up the idea that I raised with you a while back on designing a graduate course. Please pour in your ideas and whether you want to be part of it. 
This is a very rough draft: 

# Biomedical data science 

## Target population 
Graduate students that are from different backgrounds and have entered the Neuromodulation/Neuroscience/biomedical engineering program

## Course Description 
Biomedical data includes a diverse range of data types from patient data from national registeries, to biomarker data, to genetic and sequence data, to electrophysiological recordings from human or animal models, to simulations; usually covering multiple spatio-temporal scales. These data are usually high dimensional, noisy and fragmented. Handling such data is challenging and understanding it is the very important first step in a data-driven approach to build predictive models. This course introduces techniques to analyze biomedical data using programing languages Python and R. The focus of the course is to integrate reproducible research principles such as well-documented modular coding, correctness of procedure, and interpretability of results and presentation of outcomes of the analysis. 

## Learning Outcomes 
- understand complications related to using and analyzing biomedical data; with a focus in high dimensional data
- write well written, well documented modular code
- manipulate, clean and filter data and organize data properly 
- discriminate between interpretable and black box models and correctly setup validated statistical models
- generate publication quality presentation of outcomes and effectively communicate technical content
- productive collaborative work in a diverse team

## Ideas for course syllabus
Programming
- Intro to Python/R 
- Data cleaning/wrangling - tidy data
- From Data Exploration to Publication-Quality Figures
- scientific computing skills: version control and GitHub; documentation; modular coding;
Quantitative methods
- best practices with high dimensional biomedical data
- dimensionality reduction, visualization and signal feature analysis
- time series analysis 
- statistical learning framework (machine learning algorithms)
[potential models
    - Generative Models
    - linear regression/mixed effects/multivariate; 
    - Bayesian network/autoregressive model
    - Boltzmann machine
  - Discriminative Models
    - logistic regression
    - SVM
    - Neural networks]
- predictive-analytic models: Choosing the Best Model
  - AIC/BIC
- Project wok 

## Evaluation
- Project based; small groups (O:3) 
  - students will make a project plan that includes scope, significance, deliverables and milestones; overall the projects should have several phases
      - phase 1: defining the project, deciding the data, roles, etc.(including a code repo from a predefined list)
      - phase 2: code
        deliverables:
        - successful contribution to code repo (merged pull request)
        - proper documentation
        - demo/tutorial notebook 
        - presentation + live demo
        - update to either CRAN or PYPi 
      - phase 3: analysis
        deliverables:
        - conference report with publication quality figures
        - notebook to reproduce each of the quantitative results
        - presentation 
        - results to be deposited in an open access repository        
  - evaluation: the progress is evaluated at the end of each phase and the team will be graded for meeting the above deliverables and a clear and concise progress report. 
  *the phases are inspired from https://neurodatadesign.github.io/Syllabus/*

**Comment by SaraMati** [comment]
a few notes: 
- the project and lectures can go in parallel from the beginning of the term or after the programming section 
- the list of statistical models seems long, it doesn't mean that part is the focus of the course
- the focus of the course is not to teach python or R from scratch either. assumption is that either people have a background or will catch up on their own. the main concepts can be reviewed  and stressed upon in the first lectures.  
- also to teach how to integrate the two languages, e.g . have python for the raw data processing and R for the the statistical methods?

**Comment by SaraMati** [comment]
@lwjohnst86
true, the course may be fit for a one year course. this first draft was more for you (UofT council folks) to see if you are up to develop another course based on the r-course. 

ans yes, we should teach the languages. This is meant to differentiate the course with the computer science programming courses. I think the approach in teaching programming languages through scientific applications in the carpentaries and the r-course is good. 

So, I don't quite understand your comment on separating the coding/programming from modelling/data handling? Isn't the r-course a combination? isn't the approach to teach programming for science, and hence in the lectures we have to talk about some models! I agree that then in the project part we should leave it to students and what is relevant to the projects. [a review of the r-course project can be help]. 

In general, I agree that the content of the course should be better determined. 
there are factors that should be determined from the institute side that affects the content: 
- if it is one year or one term course
- since the institute is multi-disciplinary, the course can be targeted to (i.e. mandatory for) specific group: like only students from life-sciences or only students from engineering. 
I will update here upon my meeting with the institute. 

Thanks for your input, I assume, the content will form through such discussions between people who sign up for developing the course.

**Comment by lwjohnst86** [comment]
@SaraMati yes, you are right about the rcourse and the coding vs modelling. I more meant to make sure it is solidly in the area of applying those models in a practical and hands on environment, rather than in the theory and details of the modelling/statistics.

Looking forward to hearing what they say about the idea. As I said, I can contribute material that overlays with what I plan on doing anyway :)
