### ISSUE TITLE
Coffee and Code - Second Cup Card 

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/council#289]
I remember @mbonsma suggested we could buy people coffee/tea etc if they come to Coffee and Code, but receipts could start to get a bit cumbersome and if it's a giftcard, we'd have to pass it around to whoever goes each time. I asked the cashier at the Grad House and she says what they do at other stores is have a card with some money loaded onto it which she keeps by the cash in an envelope.
 
I think we thought of this too but weren't sure if they could do it, but they can :) We can also put a note saying only valid "Tuesdays 9-11am, 1 drink" and she'll put any orders on that card specifically. We just need to keep the receipt from when it was bought. Does this sound reasonable? Also I think we should keep this for non-exec members only?

**Comment by mbonsma** [comment]
Great idea! I agree, non-exec members only is a good idea, at least for starters.

**Comment by linamnt** [comment]
I forgot to update, but we do have a card at the Second Cup. It's loaded with $20. Just ask for the "UofT Coders" card.
