### ISSUE TITLE
Spring/Summer 2019 Lesson Schedule

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/council#293]
- Intro Python
- Intro R
- Intro Git
- Journal club: citation managers (based on survey)
- Python: Object Oriented Programming (based on survey)
- Mapping in R/Python
- humanities topics x 2-3 (can also get DHN to suggest topics they'd like to see, whatever the instructors want to teach)

Please suggest here any others you think are interesting, we can refer back to the survey as well as more people fill it out.

**Comment by SaraMati** [comment]
- Designing data analysis workflows
and I have a specific date/speaker proposal for it: **June 20th**, Julia Sprenger one of the contributors of [Elephant](https://elephant.readthedocs.io/en/latest/index.html#)

I will explain more in the meeting if others think it's a good idea

**Comment by SaraMati** [comment]
Some intermediate Python? 
- Network graph visualisation in Python

**Comment by aays** [comment]
Following yesterday's meeting, how does tentative schedule look? I'd like for us to keep up the 'topics'-based scheduling we had last year in a general sense, but we don't have to stick to it too closely. I relied a fair bit on the survey in deciding these.

I currently have the lessons grouped by topic, but we could also stagger them out (i.e. R the first week, Python the next) depending on how people feel grouping went last year.

**R**
May 23 - Intro to R (Margot)
May 30 - Data visualization in R with ggplot2
June 6 - Statistics in R

**Python**
June 13 - Intro Python
June 20 - Designing data analysis workflows (tentatively)
June 27 - Python - Object Oriented Programming

**Reproducible science**
July 4 - Intro Bash
July 11 - Intro Git
July 11 - Journal Club/Lightning Demos - academic workflows (tmux etc)
July 18 - Collaborating with Git

I'm not sure how the gadgets/hardware sessions pan out, or what's a good time for them - thoughts?

Also @SaraMati I like the sound of that topic! What would it involve? I've included it in the tentative schedule above for now.

**Comment by linamnt** [comment]
Yes this looks great! I like the idea of maybe trying the chunked together lesson topics. Might help build momentum!

**Comment by aays** [comment]
@linamnt I like that idea! People seemed pretty jazzed about machine learning in the survey (as always) so that could be a special topic?

**Comment by SaraMati** [comment]
great, I'll ask the instructor to send a blurb. 
and I think the lesson program is great. and we can have the last 6 sessions of the summer for applied topics as Lina suggested.

**Comment by aays** [comment]
@SaraMati Just checking in - any updates from the instructor?

**Comment by SaraMati** [comment]
sent an email now, will post the blurb as soon as I get it

**Comment by SaraMati** [comment]
@aays the blurb: 

Systematic and reproducible management of your scientific workflow based on examples from electrophysiology
or
How to perform data analysis using snakes and elephants

In this session I will introduce two tools which help in setting up reproducible scientific data analysis workflows: 
1) The workflow management system [*Snakemake*](https://snakemake.readthedocs.io) permits to define workflows in a pythonic, modular, human readable way using rules to define elemental processing steps. Snakemake workflows can be executed locally but also integrate well with distributed data and cluster computing.
2) The electrophysiology analysis toolkit [*Elephant*](http://neuralensemble.org/elephant) is an open-source package for the analysis of spiking as well as LFP activity. Elephant is based on the [*Neo*](https://neo.readthedocs.io/en/latest/)  framework, which provides a bridge to various different electrophysiology data formats and represents the data in a stardardized, annotated fashion.

To participate in the session, please set up a conda environment and install the required packages:

```
# setting up the environment
conda create -n demo python=3
conda activate demo

# installing required packages
conda install -c conda-forge bioconda::snakemake
pip install elephant
```

**Comment by aays** [comment]
Thanks @SaraMati! Sounds like a great lesson to me. 

All, how does this look as a final schedule? Let me know whether you have any changes/suggestions. Once enough people sign off I'll get to posting a call for instructors.

**R**
May 23 - Intro to R (Margot)
May 30 - Data visualization in R with ggplot2 (Ahmed)
June 6 - Statistics in R

**Python**
June 13 - Intro Python (Lina?)
June 20 - Designing data analysis workflows (tentatively)
June 27 - Python - Object Oriented Programming

July 4 - Coworking

**Reproducible science**
July 11 - Intro Bash
July 18 - Intro Git
July 25 - Journal Club/Lightning Demos - academic workflows (tmux etc)
Aug 1 - Collaborating with Git

**Special topic: machine learning**
Aug 8 - Machine learning: introduction to concepts
Aug 15 - Python: image processing

Aug 22 - Coworking

I'm not sure what to do with Aug 29th - I could leave it open for now so there's room for another lesson within the 'series' if anyone has any ideas? If not, perhaps we could have a break that week in preparation for the Fall semester to come?

**Comment by mbonsma** [comment]
End of August is usually the slowest time of year - I think it would be fine to leave that blank.

**Comment by aays** [comment]
@mbonsma Good to know - thanks!

**Comment by aays** [comment]
Also, @linamnt I just noticed that you mentioned something about people from DHN wanting to teach? I'm a bit out of the loop but if that's still a thing, we can totally edit the schedule to make room for some digital humanities sessions

**Comment by linamnt** [comment]
Ya they never got back to me with instructors. We can revisit for the fall semester?

**Comment by aays** [comment]
@linamnt Sounds good!
