### ISSUE TITLE
Hangouts On Air is Deprecated

### ISSUE THREAD

**Issue by margot-l** [UofTCoders/council#299]
Hangouts on Air is no more so we need an alternative for streaming. The current youtube alternative only allows for [webcam streaming](https://support.google.com/youtube/answer/9228389?hl=en&ref_topic=9257984).

The other alternative is to use an [encoder](https://support.google.com/youtube/answer/9227510). Based on the [list of encoders youtube provides](https://support.google.com/youtube/answer/2907883) it seems they normally require the screen sharer to download software which of course works less well or requires us to purchase a device.

**Comment by QuLogic** [comment]
This is also going to be annoying for authentication purposes. Before, we could just let people login on their own account, but using an encoder means we need to provide our stream key (which is less than work than a username+password, but also more complex looking) and then we'd have to be sure to reset it after every stream (there's no logout for stream keys).

**Comment by aays** [comment]
This has been discussed in the Gitter a bit, but I'll add it here as well: we used [StreamYard](https://streamyard.com) for our Intro to Machine Learning session two weeks ago and it went fairly well. There is full support for streaming directly to YouTube and it also maintains the 'call' like functionality of Hangouts on Air, in addition to providing a bit more control on the host's end over what's shown on screen beyond just a 'Start Broadcast' button. The only problems are that it creates a (relatively unobtrusive) watermark in the top right and was also slightly heavy on both the host/instructor's computers.

**Comment by linamnt** [comment]
Closing for now as we've switched to [StreamYard](https://streamyard.com/) successfully this semester.
