### ISSUE TITLE
When committing to this repo use local git config

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#32]
As per @QuLogic suggestion, we should make local changes to the git config for the council repo when ever we commit/push/etc. That way we never forget to do `git commit -S` for GPG signing.

Code to make this happen for each local repo is:

```
git config commit.gpgSign true
```

This makes the default behaviour in the `council` local repo to use GPG signing.

**Comment by mbonsma** [comment]
Does that alias mean that every commit from our machine to any repo is secure? Or is it repo-specific?

**Comment by lwjohnst86** [comment]
It's repo specific. If you want it for all repos use `git config --global`

**Comment by QuLogic** [comment]
I meant the setting, actually: `git config commit.gpgSign true`.

**Comment by lwjohnst86** [comment]
What's the difference between the two code bits? As in it doesn't require an alias, that's it? Are they equivalent in outcome? The non alias makes sense tho, I'm just curious

On 18 August, 2016 3:34:19 PM EDT, Elliott Sales de Andrade <notifications@github.com> wrote:
>I meant the setting, actually: `git config commit.gpgSign true`.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/UofTCoders/council/issues/32#issuecomment-240831946

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by QuLogic** [comment]
From `man git-config`:
> To avoid confusion and troubles with script usage, aliases that hide existing Git commands are ignored.

So it turns out that that alias doesn't work as is. You'd have to give it a different name.

**Comment by lwjohnst86** [comment]
Assuming everyone did this. Closing
