### ISSUE TITLE
Doodle polls should be done thro a UofTCoders account

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#42]
It isn't set up yet, but any doodles should be done through a UofTCoders account so that other council members can access it when needed. Otherwise a doodle can fall through from someone else's account.

**Comment by mbonsma** [comment]
Not sure if this has been addressed, but we do have a UofT Coders gmail account - Lina or I can give you the password at some point.

**Comment by linamnt** [comment]
Doodle polls now using the uoftcoders@gmail.com account which all execs should have access to.
