### ISSUE TITLE
Schedule and include in constitution annual audit and review of finances

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#44]
I think this might be a good idea to formalize/regulate this so that future councils ensure that finances make accounting sense and hold up to professional audits. Would need something to incentivize doing it though... Thoughts?

**Comment by mbonsma** [comment]
Like something to incentivize beyond "you should do it because you're a good person"? Maybe we could make it a fun party, like how no one wanted to do GPG-signing but it was actually really fun?

**Comment by joelostblom** [comment]
This should happen twice a year in March and October.
