### ISSUE TITLE
Policy to ensure at least one council member goes to session + backup

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#45]
I dropped the ball on today's session and forgot to go to give the adaptor (I hope everything went well). I'm thinking we need a more formal process to say who is definitely going and have a backup person as well. Ie. for keys and for snacks, etc.

One possible mechanism may be to use the 'assign' option on the issues and assign ourselves to the Issues in the Events repo. Then confirm with a second to also be there as a backup (in case something happens in transit or something). And maybe even get a list of people willing to act as surrogate members (any way to give recognition to that role?).

Thoughts?

@QuLogic @linamnt @lcoome

**Comment by mbonsma** [comment]
I like the assign idea! Do we all have the ability to assign each other to issues in the events repo?

As far as surrogate members, in the past I've asked @jladan or Sophie to open the door if I wasn't going to be around.

**Comment by lwjohnst86** [comment]
See https://github.com/UofTCoders/council/pull/50/files#diff-47d8788a1677b5131ef8e63b19a1c4be We'll use the assign function.
