### ISSUE TITLE
Link to website for installation instructions for most languages

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#49]

**Comment by mbonsma** [comment]
This could also be listed in the main studyGroup repo in case anyone not on exec wants to take a crack? Although I see you've assigned yourself already.

**Comment by joelostblom** [comment]
Is this the same as https://github.com/UofTCoders/studyGroup/pull/217? Or is this creating a link on the website to the file that was created in the aforementioned pull request?
