### ISSUE TITLE
Reimbursement receipts for Lina + Maddy

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#58]
Just so it's not forgotten :)

Lina's receipts: https://github.com/UofTCoders/council/blob/master/treasurer/receipts/2016-12-08-Drinks-GSUPub-Lina.pdf

Maddy's receipts: https://github.com/UofTCoders/council/blob/master/treasurer/receipts/2016-12-08-Snacks-GSUPub-Maddy.pdf

Also, how do we handle the Mozilla fund we got?

**Comment by mbonsma** [comment]
I'm supposed to submit receipts from the event on Expensify, and then I'd be reimbursed directly. I can do that with both of our receipts and then pay Lina back, is that okay?

**Comment by lwjohnst86** [comment]
That should be fine. But will they allow alcoholic submissions too?

To make use of the funds, could you also do these receipts too?

- https://github.com/UofTCoders/council/blob/master/treasurer/receipts/2016-12-07-Snacks-BloorstreetMarket.pdf
- https://github.com/UofTCoders/council/blob/master/treasurer/receipts/2016-12-06-Snacks-BloorstreetMarket.pdf

And if alcoholic is fine, could you also submit this one?

- https://github.com/UofTCoders/council/blob/master/treasurer/receipts/2016-12-08-Drinks-GSUPub-Luke.pdf

**Comment by lwjohnst86** [comment]
I've started a PR #57 for my expenses but if we can use the Mozilla fund, maybe we can close that PR?

**Comment by mbonsma** [comment]
I submitted all these receipts, here's a copy of the expense report submitted to Mozilla: https://github.com/UofTCoders/council/pull/59
