### ISSUE TITLE
Course development and council position

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#66]
Just to get things started. In the meeting (minutes [here](https://github.com/UofTCoders/council/pull/65/files#diff-7deb7d434606f02d061adac1abf50154)), we talked about starting a course for showing the workflow of data analysis and how to properly code. (likely an extension of [this](https://cbahlai.github.io/rqm-template/)).

We could include a new council position if @joelostblom is interested. We can talk about this more.

Any todos we can start adding here. I might soon set up a repo for the project/fork Christie's/whatever specific for this project.

**Comment by linamnt** [comment]
Woops I just posted about it without seeing this, I'll just copy as a comment here.

**Comment by linamnt** [comment]
### First Steps
1. How many co-instructors are allowed for a single course?
2. Which department will sponsor the course? 
    - Look for the largest department in SGS
    - possibly through FacMed
    - consider an undergrad 4th year course 
    - Joint courses through two departments
3. Are graduate students allowed to instruct other graduate students?

**Comment by lwjohnst86** [comment]
Haha, doing it at the same time!

Also, to add:

- Cross-list the course as grad/undergrad?
- Try to get it as an interdepartmental course?

**Comment by linamnt** [comment]
I think we should also prepare some sort of way to present our proposal (a powerpoint, or talk) for when we go to departments so we at least indicate we're prepared and have thought about this. I've gone in to do proposals to administration for other things as part of student council and they don't take lightly to underprepared, unpolished presentations for something like this.

**Comment by lwjohnst86** [comment]
Definitely! That is something I would not do, basically shoot ourselves in the foot if we did... I wonder if we should get like a survey from students about how they learn coding... Too much maybe?

**Comment by linamnt** [comment]
IMS Website: IMS continued to expand dramatically, becoming the largest graduate unit in the Faculty of Medicine, and the fifth largest graduate unit at the University of Toronto.

**Comment by lcoome** [comment]
Late to this party, sorry - if a grad course is the way IMS is good because they get little to no formal training in data analysis. Great that you found out it is the biggest.


It may end up that we need to pitch it as an undergrad course.


And yes yes yes to the presentation.


If any survey is to be done, it is going to need to argue for the NEED for a course like this, and demonstrate strong interest from the students. It is not a bad idea, but who is our target audience? We need to narrow down our options somehow - cross-listed, grad vs undergrad, interdiscplinary vs single dept, which one of the many programs/depts to pitch to.


We can consider both UTM and St. George campuses I think. Definitely important to know how many co-instructors are allowed. You all need to look into whether you are far along enough in your program to act as course instructors, also - in Psychology you must be in your third year for instance. Those who are not eligible could possibly be teaching assistants and/or guest lecturers. I did not go here for undergrad - does anyone have a sense of when students begin signing up for courses in the summer? There must be deadlines for submitting/proposing courses and such. It might vary by department.

________________________________

**Comment by joelostblom** [comment]
Sorry @lwjohnst86 @linamnt, I totally missed that you opened this issue. Thanks @lcoome for bringing it to the top of my inbox again!

I can stay after the meeting today if anyone has time just briefly discuss the immediate next steps.

**Comment by lwjohnst86** [comment]
No worries @joelostblom! I will have to run half way through today, but we should definitely discuss next steps. At the next meeting we'll invite you along! ... not sure when the next meeting will be, but we can figure that out later!

**Comment by lcoome** [comment]
Definitely lots to discuss. Unfortunately I can't make it tonight but keep me posted on the conversation.
________________________________

**Comment by linamnt** [comment]
We didn't really get a chance to talk much about it, but I think we need to focus on figuring out when deadlines are (ask around your departments if possible?) and then working on our pitch presentation, and potentially get a survey going in the department of interest.

**Comment by lcoome** [comment]
Agreed
________________________________

**Comment by joelostblom** [comment]
I spoke to the grad coordinator for our program, who unfortunately didn't know when the deadline would be, but he outlined the general procedure for launching a course:
1. Find a department that would like to sponsor our course (as mentioned here earlier).
2. This department would help us dig up details around exactly what is required to launch a course at UofT.
	- Is there faculty willing to teach the course?
	- How many co-instructors can there be?
	- Do all teachers need to hold a PhD degree?
        - Regarding this, students at our department (IBBME, biomed engineering) need to be taught a certain amount of hours from a lecturer holding a PhD. This is in order to receive an engineering certification by some national engineering association. One of my colleagues was denied teaching a class because of this. Other departments might have similar requirements.
3. Put together a new course application with the sponsoring department and sent it in to the provost office at UofT.

Another colleague of mine mentioned that she might be able to get more information or put us in contact with someone from Molecular Genetics (which has a newly started program in quantitative biology) or Human Biology who had some experience from teaching there. She also mentioned that departments are often interested in additional courses since that will bring in some money, especially if it is online courses where a lot of undergrads can enrol...

One thing I am wondering - which is our target audience for this course? Is it geared more towards science students who are likely never to take any other course on this topic and aim to become more traditional researchers, or do we primarily target students who are interested in dwelling into the more quantitative paths of their respective field?

**Comment by lcoome** [comment]
RE our target audience, I would vote for the former group. Would love to hear what everyone else thinks.

________________________________

**Comment by joelostblom** [comment]
I just heard back regarding the deadline

> I'm not exactly sure when the deadline is but the process can take a while so the time line for September is actually tight.  The course would first need to be approved by all Chairs and Directors within a faculty (e.g.: Engineering or Medicine) and I believe their last meeting for the year will be in March.  If approved, it then needs to go to Governing Council for final approval and their last meeting is in April or May.

**Comment by lcoome** [comment]
Not surprising, should we be putting together a proposal of some sort soon? And it would be good to have an answer to the question of how many co-instructors can teach one course. Also if we go for, say, engineering, but none of us are engineers, does that pose a problem? Maybe that interdisciplinary option is something to look into further?
________________________________

**Comment by mbonsma** [comment]
Target audience: I think traditional science students with no other access to coding instruction (the former group). Timeline and pitch - it sounds like we should make direct contact with a department as soon as possible, even just in the form of an email with a very brief pitch. From there we can find out about # of instructors, deadlines, etc. 

How about we make a file in this repo to work on an email-friendly pitch?

**Comment by joelostblom** [comment]
Yes, please go ahead! I am making a list of similar courses ad UofT, will post it here soon.

**Comment by joelostblom** [comment]
Phew, there is a fair number of courses at UofT...
Fortunately, I did not find anything quite like the outline of the RQM course @lwjohnst86 linked earlier. The most similar was this one

- Physical and Environmental Sciences
    - [EES1137H Quantitative Applications for Data Analysis](https://www.utsc.utoronto.ca/gradpes/ees1137h-quantitative-applications-data-analysis)

Which is still not that similar. That course is offered through [SciNet](https://support.scinet.utoronto.ca/education/go.php/306/mods/course_summary/index.php/ib/1//p_course/306).  Their courses can be taken by grad students in  Physics, Astrophysics, Chemistry, Physical and Environmental Sciences, and Ecology and Evolutionary Biology. They had some courses similar to what software carpentry offers including introductions to Unix and scientific computing.

Other than that, there was a few statistics-focused courses from various departments that I suspect might include some of part 1 and 2 from the RQM course, but also a lot of other things and not the last two parts. Below is a list of all the departments I thought might offer similar courses. I went through their grad and undergrad courses and listed anything that was remotely related. Please add if I missed something.

#### Departments and courses
- Biochemistry
    - BCH441H - Bioinformatics
- IBBME
- Chemistry
- Chemical engineering (Grad only)
- Cells and systems biology
    - CSB1472H/S, LEC 0101 – Computational Genomics and Bioinformatics
    - CSB 352H1S – Bioinformatic Methods
- Biotechnology (Grad only)
- Ecology and evolutionary biology
    - EEB225H1 - Biostatistics for Biological Sciences
- Electrical Engineering
- Health Informatics
- Immunology
- Math
- Mechanical & Industrial Engineering
    - MIE1624H Introduction to Data Science and Analytics
- Materials science and engineering
- Medical biophysics
- Medical Science
- Molecular genetics
    - A Practical Course in Programming for Biologists
- Nutrional sciences
- Pharmacology
- Physics
- Physiology
- Psychology
- Public health
    - A bunch of biostat courses geared towards epidemiologists that together probably covers much of what is in our course.
- Statistics
    - STA1007H Statistics for Life and Social Scientists
    - STA1001H - Methods of Data Analysis 1

And last a congrats to @mbonsma! I saw on the physics website that you just got an NSERC award, sweet! I got Sid on my committee btw, always super nice =)

**Comment by QuLogic** [comment]
SciNet also has some related courses.
* [Introduction to the Linux Shell SCMP101](https://support.scinet.utoronto.ca/education/go.php/309/index.php/ib/1//p_course/309)
* [Intro to Scientific Computing with Python SCMP112](https://support.scinet.utoronto.ca/education/go.php/264/index.php/ib/1//p_course/264)
* [Scientific Computing for Physicists PHY1610](https://support.scinet.utoronto.ca/education/go.php/276/index.php/ib/1//p_course/276)

Some of these can be applied for course credit, e.g., in Physics you can take 3 "modules" (not necessarily from SciNet) and turn that into a course.

**Comment by joelostblom** [comment]
Yes, those were the ones I was referring to! I think they seem more similar to the software carpentry material, than the RQM course. I wonder if SciNet would be interested/could facilitate us launching this course somehow... Or maybe that just adds another layer of bureaucracy.

**Comment by lcoome** [comment]
What does SCMP stand for? Are these interdisciplinary or comp sci course codes?

________________________________

**Comment by QuLogic** [comment]
I'm not sure SCMP stands for anything officially. If your department supports it, you can use them as part of a modular course. In Physics, you can create your own course [PHY2109H Y](https://www.physics.utoronto.ca/students/graduate-courses/current/copy_of_phy2109h-y) that consists of 3 modules.

**Comment by lwjohnst86** [comment]
Excellent work @joelostblom on looking for these courses! I've put the list together here #85 as a reference that we can update and maintain as we go along.

**Comment by lwjohnst86** [comment]
Also, I also agree that the target should be students who will likely go to be traditional researchers and who don't have more formal training in quantitative/computational analysis/methods

**Comment by joelostblom** [comment]
Thanks for putting that list together!

I was reading about the creator of the RQM, Christie Bahlai, and [found this post](http://grazielladirenzo.weebly.com/bayes-the-way/open-science-why-is-everyone-talking-about-it) on one of her colleague's blog (I kind of wish I worked in that lab, just look at [their lab photos](https://msu.edu/user/ezipkin/lab-members.html)!). Especially motivating is this snippet about how students from the RQM class went on to publish a paper in Royal Society Open Science.

> III. I’d like to share with you what I would consider a success story in the Open Science community.
> - Dr. Christie Bahlai recently taught [a course](https://github.com/cbahlai/OSRR_course) on open science within the past year at Michigan State University
> - What students did was download open data, analyze it, and provide code on Github, and write this up for publication
> - One of the groups in the class, submitted their paper to Royal Society Open Science, and one of the reviewers went on Github, downloaded their data and code, and was able to recreate the results from their paper.
> - That reviewer started a discussion with them on alternative ways to think about interpreting the results and future directions they could take the work- making the paper stronger in the end
> - Which is pretty cool, and really helpful. Check out the [published paper here](http://rsos.royalsocietypublishing.org/content/3/12/160712)!
> These are exactly the types of things that Open science is looking to 
>    - Promote openness
>    -    Reproductibility
>    -    And facilitate collaborations and discussions.

I believe this is a strong point to bring up in a pitch to a department. Rarely do student get such real world experience from a course!

I am also trying to set up a meeting with one of the course coordinators in MoGen (a friend of a friend), to get some info on how to approach the department. I'll let you know if I'm successful in case you want to join or forward me specific questions to ask.

**Comment by joelostblom** [comment]
And in addition to the GitHub link above, here is [the link to the student-led blog](https://osrrcourse.wordpress.com/2016/01/19/today-in-osrrcourse-1-19/) for her course, which they are referring to as _The Open Science and Reproducible Research course_.

**Comment by QuLogic** [comment]
A long [guide about course expectations](http://www.artsci.utoronto.ca/faculty-staff/teacher-info/AcademicHandbookUpdatedDec2016.pdf) (once it's accepted, at least.)

**Comment by QuLogic** [comment]
[Curriculum committees meetings](http://www.artsci.utoronto.ca/main/governance/curriculum-committees)

**Comment by linamnt** [comment]
maybe we can set up a "Project" page related to the development of this course? Not sure if actually useful but seems like it could be good to keep track of tasks to move this forward

**Comment by lwjohnst86** [comment]
FYI: Here's another course we could merge in with Christie's course: https://github.com/Open-Data-Science-at-SIO/RRROBOTS

We met the guy who was developing this at the Working Open Workshop in Montreal
