### ISSUE TITLE
Elections held in April?

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/council#68]
Do we still want to hold elections in April? That's what we did last year with a month in advance to nominate etc.

**Comment by linamnt** [comment]
I'm making the schedule for the semester now, it might work to have the hopefully quick election before the Hacky Hour end of April and then head off to the pub?

**Comment by mbonsma** [comment]
Yeah, that sounds good to me!

**Comment by lwjohnst86** [comment]
Yea, I think it's fine. Maybe there's someone that wants to jump in. Do we just put up the roles that are/may be available? Cause I assume none of us are planning on dropping... right? Maybe just an election to say, yea, we are fine with the current execs?

**Comment by mbonsma** [comment]
I mean we can still have a proper election - post the roles, etc, and then if multiple people run we vote, otherwise I'm assuming the current execs will run again and if there aren't multiple candidates then nothing changes.

**Comment by lwjohnst86** [comment]
Fair enough. To keep it democratic and all.

**Comment by lcoome** [comment]
Sounds fair!
________________________________
