### ISSUE TITLE
Hats? Screen cleaners? Water bottles? 

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/council#70]
What if we got some cool merch with the UofT Coders logo on it? @linamnt got me thinking! We could sell it at cost. 

My mom gets a bunch of stuff from [Rainbow Marketing](http://www.rainbowmarketing.ca/) for her job, and there are probably lots of places more local we could try, maybe something like http://www.gotmerch.ca/ or https://www.artik.com?

**Comment by lwjohnst86** [comment]
Hmm, that's an interesting idea. Or maybe slightly above cost, for assurance/wiggle room? Screen cleaners would be cool!

**Comment by QuLogic** [comment]
We might want to see how popular the stickers are (though they'll _probably_ be more popular than any of these.)

**Comment by lcoome** [comment]
Good point

________________________________

**Comment by lcoome** [comment]
unrelated but can someone put up the code review session on the website...? as of right now it looks like there isn't anything happening tomorrow

________________________________

**Comment by linamnt** [comment]
Sorry guys I fell behind on all that...I'll do that within the hour.
