### ISSUE TITLE
How to go about reimbursement process?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#8]
Hey @mbonsma @linamnt @QuLogic, I need some advice/concensus here. I've been trying to work out how to go about getting reimbursement information for reimbursements. 

In my grad council (NSGSA) I have a pdf of a form that lists the receipts and claims, and has a signature section. Anyone who wants to get reimbursed has to either scan that form and send to me or give me it in person.

However... I don't really like that system since it relies on scanning and paper copies. Do any of you know of some way that we could attach a 'digital' signature to the reimbursement, keeping it as a plain text md file or something. In the spirit of GitHub etc...

What I have thought so far is to have a template for a reimbursement form in `md`, have them either use an issue with the information or submit a pull request, and in the repo have a link to the issue/pull request within the `reimbursement.md` file or some such... Then we could get like any of the council 'approve' the issue/pull request so that there is like internal checks, etc. 

I might not be making sense here...

Thoughts??

**Comment by QuLogic** [comment]
Digital images of a signature on paper are of course useless. But you _can_ digitally sign the text file with a PGP/GPG key. Git commits are also not themselves inherently verifiable, but you _can_ sign them with a PGP/GPG key as well. In fact, GitHub recently added [some UI to show verified commits](https://github.com/blog/2144-gpg-signature-verification).

**Comment by lwjohnst86** [comment]
Hmm, sounds interesting. But is that easy to set up? Like for those looking to get reimbursed, is this a fairly simple way of validating who is asking for the reimbursement?

... keeping in mind this is really more for proper record keeping and for possible future audits, that sort of thing. Not super necessary from a security standpoint or anything.

**Comment by QuLogic** [comment]
I sometimes see complaints about the UI, but that's usually about signing emails. And how can we complain when using `git`...

It's about the same level as setting up an SSH key (so not too difficult), except that there's an extra step where we all sign each other's keys so we know to trust them.

**Comment by mbonsma** [comment]
I like the idea of using a GitHub PR or something as a reimbursement request. This GPG UI thing sounds cool. If we add detailed steps to the reimbursement template, I don't mind asking people to do it. (Realistically, reimbursement requests won't come from people who aren't very active in the group though, so maybe it won't be necessary.)

**Comment by QuLogic** [comment]
> Realistically, reimbursement requests won't come from people who aren't very active in the group though, so maybe it won't be necessary.

Yes, that's true, but that makes using GPG easier since we only have to set up a few people. We could have a key signing at one of our non-lesson weeks.

**Comment by lwjohnst86** [comment]
I also like this GPG thing. We could get all of us set up and it would be easier to then verify the PR as the person seeking reimbursing. Then maybe include a link to the PR in the reimbursement file? I'll write something up and you guys can look it over.

**Comment by lwjohnst86** [comment]
Resolved in #12
