### ISSUE TITLE
Add directions to MP on website

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/council#80]
@lcoome pointed out that we don't have good directions to MP on the website, and in the event posts it just says 'MP' or sometimes 'Mclennan Physical Labs'. 

We could resume adding some directions at the bottom of event issues, like this: https://github.com/UofTCoders/Events/issues/27, and/or we could add a link on the website to the google map and include some text directions. 

Should this be a separate page on the website that is linked under 'Contact'? Any thoughts on the what's the best way to do this?

**Comment by joelostblom** [comment]
For simplicity, I would suggest just changing the text under the "Events" section on the website to something along these lines:

> All our events are held in Rm 408 on the 4th floor of [the Burton Tower in the McLennan Physics building](http://www.openstreetmap.org/way/14748316), at the corner of Huron Street and Russel Street.

And maybe remove the current line "Our upcoming and recent events".

For each event posted on GitHub, include either

>  Rm 408 on the 4th floor of [the Burton Tower in the McLennan Physics building](http://www.openstreetmap.org/way/14748316).

or possibly just

> [MP408](http://www.openstreetmap.org/way/14748316)

**Comment by linamnt** [comment]
Agreed, this is a good idea!
We could put it into the event posting template. Also, I think the more descriptive one is fine for event postings so they don't have to do double clicking unless they don't know where that building is.

**Comment by linamnt** [comment]
Just added a pull request https://github.com/UofTCoders/Events/pull/93 to the event template. can work on adding to website a bit later as well if we're okay with putting it under the title as @joelostblom suggested

**Comment by mbonsma** [comment]
Awesome, @linamnt! I like @joelostblom's suggestion for the website.

**Comment by linamnt** [comment]
See https://github.com/UofTCoders/studyGroup/pull/242 for website update.
