### ISSUE TITLE
SWC CCR

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/council#87]
Hey there are currently 10 students that want to get CCR for attending SWC (in the SWC folder of our uoftcoders@gmail.com)
Did we take attendance for both days and should we be checking to see if they did indeed attend both?

**Comment by lcoome** [comment]
We didn't take attendance on the second day... Madeleine, did I give you the attendance sheet?

________________________________

**Comment by mbonsma** [comment]
Yup, I have the attendance sheet. Everyone who emailed about CCR is highlighted on the attendance sheet except two people who aren't on the printed list at all that I can see. I'm not too worried about checking up on attendance though - that's what the exercise is supposed to cover.

**Comment by linamnt** [comment]
That's true, if they can do the exercise I guess they deserve the credit.
Weird about the missing name though, they could be one of those three
tickets bought under one person's name, might be worth looking into though.

**Comment by mbonsma** [comment]
One of them definitely is, his email signature says he's from that lab.
