### ISSUE TITLE
Put up new position on website

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#88]
After election?

**Comment by linamnt** [comment]
Yeah, did we decide what the name of the role is? And the responsbilities? Generally I got the idea it's to implement the new course and be the primary liaison once it's established between University of Toronto and UofT coders, or was it more or a general "Lesson Developer"?

**Comment by lwjohnst86** [comment]
I like more 'Course developer'. Other thoughts? I think the position is
more for the specifics of the course rather than the code-along lessons.

**Comment by joelostblom** [comment]
I think "Course Developer" and "Course Coordinator" are good choices.
