### ISSUE TITLE
Thoughts on cheques being online?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/council#9]
@linamnt @mbonsma @QuLogic 

What do you all think of cheques being put online? I've already put one up, but I would like a concensus here on the ...ethics?... safety? ... of doing this.

**Comment by linamnt** [comment]
I personally don't think cheques should be online though I think just the
cheque number in a sheet (name, the two who signed off on it, purpose,
amount, cheque#) for each reimbursement for our records is best?

On Fri, May 13, 2016 at 4:02 PM, Luke W Johnston <notifications@github.com>
wrote:

> @linamnt <https://github.com/linamnt> @mbonsma
> <https://github.com/mbonsma> @QuLogic <https://github.com/QuLogic>
>
> What do you all think of cheques being put online? I've already put one
> up, but I would like a concensus here on the ...ethics?... safety? ... of
> doing this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/UofTCoders/council/issues/9>
>



-- 
Lina Tran
MSc. Candidate | Frankland Lab <http://www.franklandlab.com/>
Department of Physiology
University of Toronto

**Comment by lwjohnst86** [comment]
Fair enough. I'll just keep it on my end, but remove it from github. 
Others thoughts?

**Comment by QuLogic** [comment]
The routing numbers are important because they can be used to set up things like direct deposit. I'm not sure if you could set up any automatic withdrawals, though. Also, knowing the address and stuff _could_ be troublesome because sometimes bank security is not as amazing as one might hope...

**Comment by lwjohnst86** [comment]
Thanks everyone. took them down. Good thing is only cheques can withdraw, nothing else. And any changes need executive signatures/permission. But got rid of them anyway. I wondered if that was a good idea *after* already had pushed it up,. hahah doh!
