### ISSUE TITLE
attendance feb 22, mar 1

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/council#90]
Anyone remember the people in attendance for last week? or yesterday too actually! Thanks! I can update the .csv if you'd rather just comment here.

**Comment by joelostblom** [comment]
I don't know last names... Derek, Kirk, Ahmed, Joel, Elliot, Luke, Old prof
from math-something that I saw in a seminar today again, John, and
Madeleine.

**Comment by linamnt** [comment]
Thanks Joel, anyone got the one from the week prior with Collaborative Github?

**Comment by mbonsma** [comment]
Collaborative GitHub was me, Elliott, I want to say @lcoome, Kirk, and Tammi?

**Comment by linamnt** [comment]
Thanks!

**Comment by lcoome** [comment]
Can confirm I was there [😉]

________________________________

**Comment by QuLogic** [comment]
I've got all the forks... (not anymore though.) You forgot Ahmed; don't have one for Kirk. Also, Serena, the presenter as there, naturally, but I don't know her department.

**Comment by lcoome** [comment]
Serena is doing her PhD in computer science.

________________________________
