### ISSUE TITLE
Person outside the exec for code of conduct issues

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/council#98]
I think this is important for a growing group. 

We can direct people to email our uoftcoders gmail if there's ever an issue with CoC violations, but in the case they feel that it's within the exec that is the problem, perhaps we can have someone outside the group be a someone to hold us accountable to? Thoughts?

**Comment by lwjohnst86** [comment]
That is an excellent point... and definitely something to think about given we're all hoping the coders will continue after us! My initial thought would be that we have someone from the university whose job it is to over see these types of issues anyway. OR like Ulife since we are an official group with them

**Comment by linamnt** [comment]
That's a good point! I'm sure Ulife has someone

**Comment by mbonsma** [comment]
Yeah I completely agree. It might be good to contact someone at Ulife and see if they can recommend anyone instead of just listing a random email address: http://www.studentlife.utoronto.ca/cld/contact-us

**Comment by linamnt** [comment]
I emailed the groups officer at student life uoft, should edit code of conduct, and contributing.md when they reply with an answer.

**Comment by joelostblom** [comment]
Could potentially get some recommendations from the [UofT Ombudsperson](http://www.ombudsperson.utoronto.ca/) if there is something similar for clubs? (Ombudsperson also happens to be one of several Swedish loan words that you guys use!)

**Comment by linamnt** [comment]
Seems groups.officer is the way to go!
